######################################################
##                                                  ##
##                SuperiorSkyblock 2                ##
##                Developed by Ome_R                ##
##                                                  ##
######################################################

enabled: true

# Set the divider for the island bank money in the total island worth.
# You can set it to 0 to disable island bank money to be calculated in island worth.
bank-worth-rate: 1000

# Should island bank balance be refunded upon island disband?
# When set to 100, all the balance will be refunded.
# When set to 0, no balance will be refunded.
disband-refund: 0

# Should transaction logs of the island bank be saved to database?
# Warning: There may be a lot of transactions, and can increase database.
bank-logs: true

# If bank-logs is enabled, whether to cache all logs to ram or not.
# When set to true, all bank logs will be loaded when server starts and be cached on ram (Improved runtime performance).
# When set to false, bank logs will be loaded only when needed, and get cached for 10 minutes before removed from
# ram. May drop performance a little, however should help when there are a lot of logged bank transactions.
cache-logs: true

# All settings related to bank interest.
# This feature is a money-generator for the islands.
# As long as the island members are online, they will earn money.
bank-interest:
  # Should the feature be enabled?
  enabled: true
  # The interval to give the interest reward (in seconds).
  interval: 86400
  # The percentage out of the bank that will be given.
  # If it's 10, then 10% out of the bank balance will be given.
  percentage: 10
  # The maximum time that the island owner can be offline in order to be rewarded (in seconds).
  # Can be -1 in order to disable this restriction.
  recent-active: 86400