pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url "https://repo.papermc.io/repository/maven-public/" }
    }
}

rootProject.name = 'SuperiorSkyblock2'

include 'Core'
include 'Bukkit'
include 'API'
include 'Bukkit:Hooks'
include 'Bukkit:Hooks:AdvancedSlimePaper'
include 'Bukkit:Hooks:AdvancedSpawners'
include 'Bukkit:Hooks:CandcSilkSpawners'
include 'Bukkit:Hooks:ChangeSkin'
include 'Bukkit:Hooks:CMI'
include 'Bukkit:Hooks:CoreProtect'
include 'Bukkit:Hooks:CraftEngine'
include 'Bukkit:Hooks:CraftEngine26'
include 'Bukkit:Hooks:EpicSpawners6'
include 'Bukkit:Hooks:EpicSpawners7'
include 'Bukkit:Hooks:EpicSpawners8'
include 'Bukkit:Hooks:EpicSpawners9'
include 'Bukkit:Hooks:Essentials'
include 'Bukkit:Hooks:FastAsyncWorldEdit'
include 'Bukkit:Hooks:ItemsAdder'
include 'Bukkit:Hooks:JetsMinions'
include 'Bukkit:Hooks:LuckPerms'
include 'Bukkit:Hooks:MergedSpawner'
include 'Bukkit:Hooks:MiniMessage'
include 'Bukkit:Hooks:MVdWPlaceholderAPI'
include 'Bukkit:Hooks:Nexo'
include 'Bukkit:Hooks:OpenJdkNashornEngine'
include 'Bukkit:Hooks:Oraxen'
include 'Bukkit:Hooks:Plan'
include 'Bukkit:Hooks:PaperMC'
include 'Bukkit:Hooks:PlaceholderAPI'
include 'Bukkit:Hooks:ProtocolLib'
include 'Bukkit:Hooks:PvpingSpawners'
include 'Bukkit:Hooks:RoseStacker'
include 'Bukkit:Hooks:RoseStacker1_5'
include 'Bukkit:Hooks:SkinsRestorer'
include 'Bukkit:Hooks:SkinsRestorer14'
include 'Bukkit:Hooks:SkinsRestorer15'
include 'Bukkit:Hooks:Slimefun'
include 'Bukkit:Hooks:Slimefun:ProtectionModule_RC13'
include 'Bukkit:Hooks:Slimefun:ProtectionModule_Dev999'
include 'Bukkit:Hooks:SlimeWorldManager'
include 'Bukkit:Hooks:SmoothTimber'
include 'Bukkit:Hooks:SuperVanish'
include 'Bukkit:Hooks:TimbruSilkSpawners'
include 'Bukkit:Hooks:UltimateStacker'
include 'Bukkit:Hooks:UltimateStacker3'
include 'Bukkit:Hooks:UltimateStacker4'
include 'Bukkit:Hooks:VanishNoPacket'
include 'Bukkit:Hooks:Vault'
include 'Bukkit:Hooks:WildStacker'
include 'Missions'
include 'Missions:BlocksMissions'
include 'Missions:BrewingMissions'
include 'Missions:CraftingMissions'
include 'Missions:EnchantingMissions'
include 'Missions:FarmingMissions'
include 'Missions:FishingMissions'
include 'Missions:IslandMissions'
include 'Missions:ItemsMissions'
include 'Missions:KillsMissions'
include 'Missions:StatisticsMissions'
include 'Bukkit:NMS'
include 'Bukkit:NMS:Spigot'
include 'Bukkit:NMS:Spigot-1_20_3'
include 'Bukkit:NMS:Paper'
include 'Bukkit:NMS:Paper-1_20_3'
include 'Bukkit:NMS:v1_8_R3'
include 'Bukkit:NMS:v1_12_R1'
include 'Bukkit:NMS:v1_16_R3'
include 'Bukkit:NMS:v1_17'
include 'Bukkit:NMS:v1_18'
include 'Bukkit:NMS:v1_19'
include 'Bukkit:NMS:v1_20_3'
include 'Bukkit:NMS:v1_20_4'
include 'Bukkit:NMS:v1_21'
include 'Bukkit:NMS:v1_21_3'
include 'Bukkit:NMS:v1_21_4'
include 'Bukkit:NMS:v1_21_5'
include 'Bukkit:NMS:v1_21_7'
include 'Bukkit:NMS:v1_21_9'
include 'Bukkit:NMS:v1_21_10'
include 'Bukkit:NMS:v26_1'
include 'Bukkit:NMS:v26_2'