######################################################
##                                                  ##
##                SuperiorSkyblock 2                ##
##                Developed by Ome_R                ##
##                                                  ##
######################################################

# Here you can set the amount of time between auto calculations of all islands.
# If you want to disable this feature, set interval to 0
# It's recommended to set the task to a high interval, as it might cause lag.
calc-interval: 6000

# All settings related to the database of the plugin.
database:
  # Choose between SQLite (localhost database) and MySQL (remote database)
  type: SQLite
  # MySQL database information
  address: 'localhost'
  port: 3306
  db-name: 'SuperiorSkyblock'
  user-name: 'root'
  password: 'root'
  prefix: ''

# Set the main command of the plugin.
# You can add aliases by adding "," after the command name, and split them using ",".
# You must have a full restart in order to apply changes for the command.
island-command: 'island,is,islands'

# Set the maximum island size. Island distances is 3 times bigger than the max size.
# Please, do not change it while you have a running islands world!
max-island-size: 200

# The default island size of all islands.
# This island size can be expanded by using the /is admin setsize command.
default-island-size: 20

# Set the default block limits of islands.
# This limit can be expanded by using the /is admin setblocklimit command.
default-limits:
- 'HOPPER:8'

# The amount of warps an island can have
# This limit can be expanded by using the /is admin setwarpslimit command.
default-warps-limit: 3

# Set the default team limit of islands.
# This limit can be expanded by using the /is admin setteamlimit command.
default-team-limit: 4

# Set the default crop-growth multiplier of islands.
# This multiplier can be expanded by using the /is admin setcropgrowth command.
default-crop-growth: 1

# Set the default spawner-rates multiplier of islands.
# This multiplier can be expanded by using the /is admin setspawnerrates command.
default-spawner-rates: 1

# Set the default mob-drops multiplier of islands.
# This multiplier can be expanded by using the /is admin setmobdrops command.
default-mob-drops: 1

# Set the default island height generation for islands.
default-island-height: 100

# Feature that adds per player world border in islands.
# If you want to globally disable it, set this section to false.
# World borders can be toggled by using the /is toggle border command.
world-borders: true

# All settings related to stacked blocks.
stacked-blocks:
  # If you want to globally disable stacked blocks, set this section to false.
  # Placement of stacked blocks can be toggled by using the /is toggle blocks command.
  enabled: true

  # Custom name for the blocks.
  custom-name: '&ex{0} {1}'

  # A list of whitelisted blocks that will get stacked when players have stack mode toggled on.
  whitelisted:
  - 'DIAMOND_BLOCK'

  # Set limits to stacked blocks.
  limits:
  - 'EXAMPLE_BLOCK:5'

  # Should blocks get added directly into the player's inventory?
  auto-collect: false

# Set a formula to calculate the island level by it's worth.
# Use {} as a placeholder for worth. Make sure you only use digits and mathematical operations!
island-level-formula: '{} / 2'

# Should the island levels be a rounded integer?
rounded-island-level: false

# How should the island top be ordered by default?
# Use WORTH, LEVEL, RATING or PLAYERS.
island-top-order: 'WORTH'

# All settings related to island roles.
island-roles:
  # This role is given to players that are not part of your island.
  guest:
    # A custom name for the role.
    name: 'Guest'
    # A list of default permissions for guests.
    permissions: []

  # This role is given to players that are co-op.
  coop:
    name: 'Coop'
    permissions:
    - ANIMAL_BREED
    - ANIMAL_DAMAGE
    - BREAK
    - BUILD
    - CLOSE_BYPASS
    - DROP_ITEMS
    - EXPEL_BYPASS
    - FARM_TRAMPING
    - INTERACT
    - ITEM_FRAME
    - MINECART_DAMAGE
    - MINECART_ENTER
    - MINECART_OPEN
    - MINECART_PLACE
    - MONSTER_DAMAGE
    - PAINTING
    - PICKUP_DROPS
    - SIGN_INTERACT
    - USE

  # The roles ladder for island members.
  # All the island member roles go here.
  #  - You can add as many roles as you'd like.
  #  - The default role for new members has a weight of 0.
  #  - Every role has all the permissions of the role before it.
  ladder:
    member:
      name: 'Member'
      weight: 0
      permissions:
      - ANIMAL_SPAWN
      - CHEST_ACCESS
      - DEPOSIT_MONEY
      - FLY
      - MONSTER_SPAWN
      - RANKUP
      - SPAWNER_BREAK
    mod:
      name: 'Moderator'
      weight: 1
      permissions:
      - BAN_MEMBER
      - CLOSE_ISLAND
      - DELETE_WARP
      - EXPEL_PLAYERS
      - INVITE_MEMBER
      - KICK_MEMBER
      - OPEN_ISLAND
      - RATINGS_SHOW
      - SET_WARP
      - WITHDRAW_MONEY
    admin:
      name: 'Admin'
      weight: 2
      permissions:
      - COOP_MEMBER
      - DEMOTE_MEMBERS
      - DISCORD_SHOW
      - PAYPAL_SHOW
      - PROMOTE_MEMBERS
      - SET_BIOME
      - SET_DISCORD
      - SET_HOME
      - SET_PAYPAL
      - SET_PERMISSION
      - SET_ROLE
      - SET_SETTINGS
      - UNCOOP_MEMBER
    leader:
      name: 'Leader'
      weight: 3
      permissions:
      - ALL

# Set the line to create the warp sign.
sign-warp-line: '[IslandWarp]'

# Set the lines of the island warp.
sign-warp:
- '&a[Island Warp]'
- ''
- ''
- ''

# All settings related to the visitors sign.
visitors-sign:
  # Set the line to create the visitors sign.
  line: '[Welcome]'
  # The line that will be displayed when the sign is active.
  active: '&a[Welcome]'
  # The line that will be displayed when the sign is inactive.
  inactive: '&c[Welcome]'

# Set the line to create the welcome sign.
welcome-sign-line: '[Welcome]'

# Set the divider for the island bank money in the total island worth.
# You can set it to 0 to disable island bank money to be calculated in island worth.
bank-worth-rate: 1000

# Settings related to the island worlds.
worlds:
  # Set the name of the islands world.
  normal-world: SuperiorWorld
  # Should the nether world be enabled?
  nether-world: false
  # Should nether be unlocked to islands by default?
  nether-unlock: true
  # Should the end world be enabled?
  end-world: false
  # Should end be unlocked to islands by default?
  end-unlock: false
  # Should the plugin optimize the island worlds?
  # When enabled, only chunks of islands will be saved from the island worlds.
  optimize: false

# All settings related to the spawn island.
spawn:
  # The location of the island. Players will be teleported to this
  # location in many events, such as disbanding islands & getting expelled from one.
  location: SuperiorWorld, 0, 100, 0, 0, 0

  # Should the spawn be protected?
  # When disabled, it's your responsibility to protect the spawn!
  # Therefore, settings will be still applied to the area if false.
  protection: true

  # A list of settings that will be enabled for the spawn.
  settings:
    - CROPS_GROWTH
    - LAVA_FLOW
    - NATURAL_ANIMALS_SPAWN
    - SPAWNER_ANIMALS_SPAWN
    - TREE_GROWTH
    - WATER_FLOW

  # Should a world border be displayed in the spawn?
  world-border: false

# When enabled, players will get teleported upon void fall.
# If they fall not in an island, they will be teleported to spawn.
void-teleport: true

# When disabled, visitors won't get damaged in other islands.
visitors-damage: false

# When disabled, coop won't get damaged in islands they are coop with.
coop-damage: true

# The amount of times a player can disband an island.
# If you want to disable this feature, set it to 0.
disband-count: 5

# Should the list of members in island top also include the island leader?
island-top-include-leader: true

# Set default placeholders that will be returned if the island is null.
# Please use the <placeholder>:<default> format.
default-placeholders:
- 'superior_island_leader:N/A'
- 'superior_island_level:0'
- 'superior_island_worth:0'

# Should a confirm gui be displayed when /is disband is executed.
disband-confirm: true

# If you want a specific spawners provider to use, specify it here.
# Providers: Auto, MergedSpawner, StackSpawners, WildStacker, SilkSpawners, PvpingSpawners
spawners-provider: 'AUTO'

# Should inventories of island members get cleared after disbanding their island?
disband-inventory-clear: true

# All settings related to island names.
island-names:
  # Should creation of islands will ask for name (/is create <name>)?
  required-for-creation: true

  # The maximum length for names.
  max-length: 16

  # The minimum length for names.
  min-length: 3

  # A list of names that will be blacklisted.
  filtered-names:
  - fuck
  - duck
  - hypixel

  # Should names have color support enabled?
  color-support: true

  # Should names be displayed on island-top?
  island-top: true

# Should players get teleported to the island after they accept an invite?
teleport-on-join: false

# Should the inventory of the players get cleared after they accept an invite?
clear-on-join: false

# Should players be able to rate their own islands?
rate-own-island: false

# Should the bonus affect the island level?
# When true, the formula will be used.
bonus-affect-level: true

# A list of default settings for new islands.
default-settings:
- 'CREEPER_EXPLOSION'
- 'NATURAL_ANIMALS_SPAWN'
- 'NATURAL_MONSTER_SPAWN'
- 'SPAWNER_ANIMALS_SPAWN'
- 'SPAWNER_MONSTER_SPAWN'
- 'WATER_FLOW'
- 'LAVA_FLOW'
- 'CROPS_GROWTH'
- 'TREE_GROWTH'
- 'FIRE_SPREAD'
- 'EGG_LAY'

# Should redstone be disabled on islands that none of the members are online?
# This should increase performance on the server.
disable-redstone-offline: true

# A list of default generator percentages for new islands.
# By default, all generators will generate cobblestone only.
# Please note: this will not work with the synced-upgrade feature of generator upgrades.
# Example: 'DIAMOND_BLOCK:50' will set 50% chance for diamond block.
default-generator:
- COBBLESTONE:95
- COAL_ORE:5

# A list of commands that should have cooldown.
# Cooldowns are in milliseconds.
# You can disable this section by using:
# commands-cooldown:
#   random:
#     cooldown: 0
commands-cooldown:
  recalc:
    cooldown: 30000
    bypass-permission: superior.cooldown.bypass.recalc

# Set the number formatting to be used.
# You can see a list of formats under the "Language Tag" column here:
# https://www.oracle.com/technetwork/java/javase/java8locales-2095355.html
number-format: "en-US"

# Should players skip menus with only one items inside them?
# When enabled, creation and island-warps menus will be skipped if only one item is inside them.
skip-one-item-menus: false

# Should visitors get teleported to spawn when pvp is enabled in an island?
teleport-on-pvp-enable: true

# Should visitors get immuned to pvp for 10 seconds when they teleport to an island that has the settings enabled?
# This doesn't apply to the spawn island!
immune-to-pvp-when-teleport: true

# A list of commands that cannot be executed by visitors.
blocked-visitors-commands: []

# Set items for the starter chest for islands.
starter-chest:
  # Should this settings be enabled?
  enabled: false
  # The contents of the chest.
  contents:
    '0':
      type: ICE
      amount: 2
    '1':
      type: MELON
    '2':
      type: TORCH
      amount: 2
    '3':
      type: BONE
    '4':
      type: LAVA_BUCKET
    '5':
      type: PUMPKIN_SEEDS
    '6':
      type: SUGAR_CANE
    '7':
      type: RED_MUSHROOM
    '8':
      type: BROWN_MUSHROOM
    '9':
      type: CACTUS
    '10':
      type: BREAD
    '11':
      type: WHEAT
    '12':
      type: LEATHER_BOOTS
    '13':
      type: LEATHER_LEGGINGS
    '14':
      type: LEATHER_CHESTPLATE
    '15':
      type: LEATHER_HELMET

# A list of commands that will be executed when an event is called.
# You can find a list of events here:
# https://github.com/OmerBenGera/SuperiorSkyblockAPI/tree/master/src/main/java/com/bgsoftware/superiorskyblock/api/events
# A list of placeholders (Not all of them work for all the events):
# %island% %player% %schematic% %enter-cause% %target% %leave-cause% %old-owner% %new-owner% %worth% %level%
event-commands:
  IslandCreateEvent: []

# A delay before getting teleported to a warp (in milliseconds).
# Players cannot move in that time, or the teleportation will be cancelled.
warps-warmup: 0

# A delay before getting teleported to your island (in milliseconds).
# Players cannot move in that time, or the teleportation will be cancelled.
home-warmup: 0

# Should liquids get updated when pasting schematics?
liquid-update: false

# A list of worlds that PvP will be enabled between island members.
pvp-worlds:
- 'PvP'

# Stop players from leaving their island by walking through the border.
stop-leaving: false

# Should the values menu be enabled?
values-menu: true

# How many chunks should be loaded in one tick by SuperiorSkyblock?
chunks-per-tick: 10

# A list of crops that will be affected by the crop growth multiplier.
crops-to-grow:
- 'CACTUS'
- 'SUGAR_CANE_BLOCK'
- 'SUGAR_CANE'
- 'MELON_STEM'
- 'ATTACHED_MELON_STEM'
- 'RED_MUSHROOM'
- 'BROWN_MUSHROOM'
- 'PUMPKIN_STEM'
- 'ATTACHED_PUMPKIN_STEM'
- 'VINE'
- 'COCOA'
- 'SAPLING'
- 'DARK_OAK_SAPLING'
- 'JUNGLE_SAPLING'
- 'OAK_SAPLING'
- 'ACACIA_SAPLING'
- 'BIRCH_SAPLING'
- 'SPRUCE_SAPLING'
- 'CROPS'
- 'WHEAT'

# Should only the back button work for closing menus?
only-back-button: false

# Should players be able to build outside their islands?
# All islands will have the size of the max-island-size * 1.5, which means islands will be connected to each other.
# It's recommended to have a low max island size when this feature is enabled!
build-outside-island: false

# The default language to be used.
# This should be the same as your language file's name.
default-language: 'en-US'

# Should world borders be enabled by default for new players?
default-world-border: true

# Should blocks stacking be enabled by default for new players?
default-blocks-stacker: true

# Should panels be toggled by default for new players?
default-toggled-panel: false

# Should fly mode be enabled by default for new players?
default-island-fly: false

# What the default color for world borders be?
# Can be BLUE, GREEN or RED.
default-border-color: BLUE