name: SuperiorSkyblock2
version: ${project.version}
main: com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin

description: Feature packed Skyblock core.
website: https://bg-software.com/
api-version: '1.13'
author: Ome_R

# Custom section used by DependenciesManager, which replaces softdepend.
class-depends:
  - AdvancedSpawners
  - CMI
  - ChangeSkin
  - CoreProtect
  - EpicSpawners
  - Essentials
  - FastAsyncWorldEdit
  - ItemsAdder
  - JetsMinions
  - LuckPerms
  - MergedSpawner
  - MVdWPlaceholderAPI
  - Oraxen
  - PlaceholderAPI
  - ProtocolLib
  - PvpingSpawners
  - RoseStacker
  - ShopGUIPlus
  - SilkSpawners
  - SkinsRestorer
  - SlimeWorldManager
  - SuperVanish
  - UltimateStacker
  - VanishNoPacket
  - Vault
  - WildStacker
  - WorldEdit

loadbefore:
  - Multiverse-Core
  - Slimefun
  - My_Worlds

libraries:
  - org.openjdk.nashorn:nashorn-core:15.4

permissions:
  superior.*:
    description: Permission for all admin & island commands
    default: op
    children:
      superior.island.*:
        description: Permission for all island commands
        children:
          superior.island.accept:
            description: Accept an invitation from a player.
          superior.island.balance:
            description: Check the amount of money inside an island's bank.
          superior.island.ban:
            description: Ban a player from your island.
          superior.island.bank:
            description: Open the island's bank.
          superior.island.biome:
            description: Change the biome of the island.
          superior.island.border:
            description: Change the border color of the islands.
          superior.island.chest:
            description: Open the island's chest.
          superior.island.close:
            description: Close the island to the public.
          superior.island.coop:
            description: Add a player as a co-op to your island.
          superior.island.coops:
            description: Open the coops menu.
          superior.island.counts:
            description: See block counts in your island.
          superior.island.create:
            description: Create a new island.
          superior.island.delwarp:
            description: Delete an island warp.
          superior.island.demote:
            description: Demote a member in your island.
          superior.island.deposit:
            description: Deposit money from your personal account into the island's bank.
          superior.island.disband:
            description: Disband your island permanently.
          superior.island.expel:
            description: Kick a visitor from your island.
          superior.island.fly:
            description: Toggle island fly.
          superior.island.help:
            description: List of all commands.
          superior.island.invite:
            description: Invite a player to your island.
          superior.island.kick:
            description: Kick a player from your island.
          superior.island.lang:
            description: Change your personal language.
          superior.island.leave:
            description: Leave your island.
          superior.island.mission:
            description: Complete a mission.
          superior.island.missions:
            description: Open the missions menu.
          superior.island.name:
            description: Change the name of your island.
          superior.island.open:
            description: Open the island to the public.
          superior.island.panel:
            description: Open island panel.
          superior.island.pardon:
            description: Unban a player from your island.
          superior.island.permissions:
            description: Get all permissions for an island role.
          superior.island.promote:
            description: Promote a member in your island.
          superior.island.rankup:
            description: Level up an upgrade.
          superior.island.rate:
            description: Rate an island.
          superior.island.ratings:
            description: Show all island ratings.
          superior.island.recalc:
            description: Re-calculates the island worth.
          superior.island.setdiscord:
            description: Set the discord of the island for island payouts.
          superior.island.setpaypal:
            description: Set the paypal email of the island for island payouts.
          superior.island.setrole:
            description: Change the role of a player in your island.
          superior.island.setteleport:
            description: Change the teleport location of your island.
          superior.island.settings:
            description: Open the settings menu.
          superior.island.setwarp:
            description: Create a new island warp.
          superior.island.show:
            description: Get information about an island.
          superior.island.stacker.*:
            description: Gives the ability to stack blocks.
          superior.island.team:
            description: Get information about island members status.
          superior.island.teamchat:
            description: Toggle team chat mode.
          superior.island.teleport:
            description: Teleport to your island.
          superior.island.toggle:
            description: Permission to use the /is toggle command.
            children:
              superior.island.toggle.border:
                description: Toggle island borders.
              superior.island.toggle.blocks:
                description: Toggle stacked blocks placements.
          superior.island.top:
            description: Open top islands panel.
          superior.island.transfer:
            description: Transfer your island's leadership.
          superior.island.uncoop:
            description: Remove a player from being a co-op in your island.
          superior.island.upgrade:
            description: Open upgrades panel.
          superior.island.value:
            description: Get the worth value of a block.
          superior.island.values:
            description: Open the values menu.
          superior.island.visit:
            description: Teleport to the visitors location of an island.
          superior.island.warp:
            description: Warp to an island warp.
          superior.island.warps:
            description: List of island warps.
          superior.island.withdraw:
            description: Withdraw money from your island's bank into your personal account.
      superior.admin.*:
        description: Permission for all admin commands
        default: op
        children:
          superior.admin:
            description: Use the admin commands.
          superior.admin.add:
            description: Add a user to an island.
          superior.admin.addblocklimit:
            description: Increase block limit for another player's island.
          superior.admin.addbonus:
            description: Add a bonus to a player.
          superior.admin.addcooplimit:
            description: Increase coop players limit for another player's island.
          superior.admin.addcropgrowth:
            description: Increase the crop growth multiplier for another player's island.
          superior.admin.addeffect:
            description: Add an island effect for another player's island.
          superior.admin.addentitylimit:
            description: Increase entity limit for another player's island.
          superior.admin.addgenerator:
            description: Add percentage of a material for the cobblestone generator.
          superior.admin.addmobdrops:
            description: Increase the mob drops multiplier for another player's island.
          superior.admin.addsize:
            description: Expand another player's island size.
          superior.admin.addspawnerrates:
            description: Increase the spawner rates multiplier for another player's island.
          superior.admin.addteamlimit:
            description: Increase members limit for another player's island.
          superior.admin.addwarpslimit:
            description: Increase the warps limit of an island.
          superior.admin.bonus:
            description: Grant a bonus to a player.
          superior.admin.bypass:
            description: Toggle bypass mode.
          superior.admin.bypass.warmup:
            description: Bypass teleport warmup
          superior.admin.chest:
            description: Open island's chest of another island.
          superior.admin.cleargenerator:
            description: Clear generator rates for a specific island.
          superior.admin.close:
            description: Close an island to the public.
          superior.admin.count:
            description: Check a block count on a specific island.
          superior.admin.delwarp:
            description: Delete a warp for an island.
          superior.admin.demote:
            description: Demote a member in another player's island.
          superior.admin.deposit:
            description: Deposit money into another player's island bank.
          superior.admin.disband:
            description: Disband another player's island permanently.
          superior.admin.givedisbands:
            description: Give disbands to a player.
          superior.admin.ignore:
            description: Ignore an island from top islands.
          superior.admin.join:
            description: Join an island without an invitation.
          superior.admin.kick:
            description: Kick a player from his island.
          superior.admin.modules:
            description: Manage modules of the plugin.
          superior.admin.mission:
            description: Change the status of a mission for a player.
          superior.admin.msg:
            description: Send a player a message without any prefixes.
          superior.admin.msgall:
            description: Send to all island members a message without any prefixes.
          superior.admin.name:
            description: Change the name of an island.
          superior.admin.open:
            description: Open an island to the public.
          superior.admin.openmenu:
            description: Open a custom menu for a player.
          superior.admin.promote:
            description: Promote a member in another player's island.
          superior.admin.purge:
            description: Purge islands from database.
          superior.admin.rankup:
            description: Rankup an upgrade for an island.
          superior.admin.recalc:
            description: Re-calculates the worth of an island.
          superior.admin.reload:
            description: Reload all configurations and tasks of the plugin.
          superior.admin.removeblocklimit:
            description: Remove a block limit for an island.
          superior.admin.removeratings:
            description: Remove all ratings given by a player.
          superior.admin.resetworld:
            description: Reset a world for an island.
          superior.admin.schematic:
            description: Create schematics for the plugin.
          superior.admin.setbanklimit:
            description: Set a bank limit to an island.
          superior.admin.setbiome:
            description: Set the biome of an island.
          superior.admin.setblockamount:
            description: Set the block amount in a specific location.
          superior.admin.setblocklimit:
            description: Set block limit for another player's island.
          superior.admin.setchestrow:
            description: Set the chest rows for another player's island.
          superior.admin.setcooplimit:
            description: Set coop players limit for another player's island.
          superior.admin.setcropgrowth:
            description: Set the crop growth multiplier for another player's island.
          superior.admin.setdisbands:
            description: Set a player's amount of island disbands.
          superior.admin.seteffect:
            description: Set the island effect level of another player's island.
          superior.admin.setentitylimit:
            description: Set entity limit for another player's island.
          superior.admin.setgenerator:
            description: Change percentage of a material for the cobblestone generator.
          superior.admin.setleader:
            description: Transfer an island to someone else.
          superior.admin.setmobdrops:
            description: Set the mob drops multiplier for another player's island.
          superior.admin.setpermission:
            description: Set a required role for a permission for all the islands.
          superior.admin.setrate:
            description: Set the rating of another player.
          superior.admin.setrolelimit:
            description: Set role limit for another player's island.
          superior.admin.setsettings:
            description: Toggle settings for a specific island.
          superior.admin.setsize:
            description: Change another player's island size.
          superior.admin.setspawn:
            description: Set the spawn location of the server.
          superior.admin.setspawnerrates:
            description: Set the spawner rates multiplier for another player's island.
          superior.admin.setteamlimit:
            description: Set members limit for another player's island.
          superior.admin.settings:
            description: Open the plugin settings editor.
          superior.admin.setupgrade:
            description: Set the level of an upgrade for another player's island.
          superior.admin.setwarpslimit:
            description: Set the warps limit of an island.
          superior.admin.show:
            description: Get information about an island.
          superior.admin.spawn:
            description: Teleport to the spawn location.
          superior.admin.spy:
            description: Toggle chat spy mode.
          superior.admin.stats:
            description: Show stats about the plugin.
          superior.admin.syncupgrades:
            description: Sync upgrade values for an island.
          superior.admin.teleport:
            description: Teleport to other islands.
          superior.admin.unignore:
            description: Unignore an island from top islands.
          superior.admin.withdraw:
            description: Withdraw money from another player's island bank.
          superior.admin.world:
            description: Unlock a world for an island.
      superior.chat.color:
        description: Gives access to use colors within island chat.