package com.bgsoftware.superiorskyblock.api.service.stackedblocks;

public enum InteractionResult {

    STACKED_BLOCKS_DISABLED,
    CUSTOMIZED_ITEM,
    PLAYER_STACKED_BLOCKS_DISABLED,
    PLAYER_HOLDING_DIFFERENT_ITEM,
    DISABLED_WORLD,
    PLAYER_MISSING_PERMISSION,
    STACKED_BLOCK_NOT_WHITELISTED,
    BLOCKS_NOT_SIMILAR,
    NOT_ENOUGH_BLOCKS,
    EVENT_CANCELLED,
    GLITCHED_STACKED_BLOCK,
    NOT_STACKED_BLOCK,
    STACKED_BLOCK_PROTECTED,
    SUCCESS;

}
