group 'Hooks:Folia'

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}

repositories {
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
    mavenCentral()
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2.build.+'
    compileOnly project(':API')
    compileOnly project(':')
}
