plugins {
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.21"
}

group 'NMS:Paper-Dialog'

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

dependencies {
    paperweight.paperDevBundle("1.21.7-R0.1-SNAPSHOT")
    compileOnly project(":API")
    compileOnly project(":")
}
