plugins {
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.21"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}

paperweight.reobfArtifactConfiguration = io.papermc.paperweight.userdev.ReobfArtifactConfiguration.getMOJANG_PRODUCTION()

group 'NMS:v26_2_folia'

dependencies {
    paperweight.foliaDevBundle("26.2.build.7-beta")
    compileOnly project(":NMS:v26_2")
    compileOnly project(":NMS:Spigot-1_20_3")
    compileOnly project(":NMS:Paper-1_20_3")
    compileOnly project(":API")
    compileOnly project(":")
}

shadowJar {
    from project(":NMS:v26_2").sourceSets.main.output
}
